name: 'Preview'

on:
  pull_request:

concurrency:
  cancel-in-progress: false
  group: release-${{ github.ref_name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
      - name: Get version
        id: get-version
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          targetPath: ./
          disableCache: true
          useConfigFile: true
          configFilePath: GitVersion.yml
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Set version
        run: |
          npm version --no-git-tag-version --allow-same-version ${{ steps.get-version.outputs.semVer }}

      - name: Restore dependencies
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm run test

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ./test-results/junit.xml

      - name: Publish test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        if: always()
        with:
          skip-step: all
          coverage-file: ./test-results/summary.json
          base-coverage-file: ./test-results/summary.json
          prnumber: ${{ github.event.pull_request.number }}

      - name: Package
        run: |
          npm run package
