name: 'Pull request opened'

on:
  pull_request:
    types:
      - opened
      - reopened

concurrency:
  cancel-in-progress: false
  group: pull-request-opened-${{ github.ref_name }}

env:
  environment: Preview${{ github.event.pull_request.number }}

jobs:
  update:
    name: Update PR description
    runs-on: ubuntu-latest
    steps:
      - name: Get issue details
        uses: gavanlamb/github-actions/.github/actions/jira/get-issue-details@main
        id: get-issue-details
        with:
          base-url: https://gavanlamb-team-1vid7fblvall.atlassian.net
          user-email: mail@gavanlamb.com
          api-token: ${{ secrets.JIRA_API_TOKEN }}
      - name: Update PR
        uses: gavanlamb/github-actions/.github/actions/pull-request/update-pr@main
        id: update-pr
        with:
          issue-identifier: ${{ steps.get-issue-details.outputs.identifier }}
          issue-title: ${{ steps.get-issue-details.outputs.title }}
          issue-url: ${{ steps.get-issue-details.outputs.url }}
          environment: ${{ env.environment }}
      - name: Send message
        uses: gavanlamb/github-actions/.github/actions/slack/pull-request-created@main
        if: always()
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          title: ${{ steps.update-pr.outputs.title }}
